#############################################################################
# Makefile for building: BVApp
# Generated by qmake (2.01a) (Qt 4.7.4) on: Tue Apr 10 21:54:03 2012
# Project:  BVApp.pro
# Template: app
# Command: c:\qtsdk\symbian\sdks\symbiansr1qt474\bin\qmake.exe -spec c:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 QMLJSDEBUGGER_PATH=C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474//qtc-qmldbg -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o bld.inf BVApp.pro
#############################################################################

MAKEFILE          = Makefile
QMAKE             = c:\qtsdk\symbian\sdks\symbiansr1qt474\bin\qmake.exe
DEL_FILE          = del /q 2> NUL
DEL_DIR           = rmdir
CHK_DIR_EXISTS    = if not exist
MKDIR             = mkdir
MOVE              = move
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make
SBS               = sbs

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_USE_MATH_H_FLOATS -DQT_XML_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
INCPATH	 =  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtCore"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtNetwork"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtGui"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include/QtXml"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/include"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/mkspecs/common/symbian"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis/sys"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/stdapis/stlportv5"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/mw"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/loc"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw/loc"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/loc/sc"  -I"C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/include/platform/mw/loc/sc"  -I"C:/dev/Dropbox/dev/nokia/BVApp/moc"  -I"C:/dev/Dropbox/dev/nokia/BVApp"  -I"C:/dev/Dropbox/dev/nokia/BVApp/ui" 
first: default

all: debug release

default: debug-winscw
qmake:
	$(QMAKE) "C:/dev/Dropbox/dev/nokia/BVApp/BVApp.pro"  -spec c:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 QMLJSDEBUGGER_PATH=C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474//qtc-qmldbg -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

bld.inf: C:/dev/Dropbox/dev/nokia/BVApp/BVApp.pro
	$(QMAKE) "C:/dev/Dropbox/dev/nokia/BVApp/BVApp.pro"  -spec c:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 QMLJSDEBUGGER_PATH=C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474//qtc-qmldbg -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

c:\dev\Dropbox\dev\nokia\BVApp\BVApp.loc: 
	$(QMAKE) "C:/dev/Dropbox/dev/nokia/BVApp/BVApp.pro"  -spec c:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\mkspecs\symbian-sbsv2 QMLJSDEBUGGER_PATH=C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474//qtc-qmldbg -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

debug: c:\dev\Dropbox\dev\nokia\BVApp\BVApp.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
clean-debug: bld.inf
	$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
freeze-debug: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1
release: c:\dev\Dropbox\dev\nokia\BVApp\BVApp.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
clean-release: bld.inf
	$(SBS) reallyclean --toolcheck=off -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1
freeze-release: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

debug-winscw: c:\dev\Dropbox\dev\nokia\BVApp\BVApp.loc bld.inf
	$(SBS) -c winscw_udeb.mwccinc
clean-debug-winscw: bld.inf
	$(SBS) reallyclean -c winscw_udeb.mwccinc
freeze-debug-winscw: bld.inf
	$(SBS) freeze -c winscw_udeb.mwccinc
debug-gcce: c:\dev\Dropbox\dev\nokia\BVApp\BVApp.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-gcce: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
debug-armv5: c:\dev\Dropbox\dev\nokia\BVApp\BVApp.loc bld.inf
	$(SBS) -c armv5_udeb
clean-debug-armv5: bld.inf
	$(SBS) reallyclean -c armv5_udeb
freeze-debug-armv5: bld.inf
	$(SBS) freeze -c armv5_udeb
debug-armv6: c:\dev\Dropbox\dev\nokia\BVApp\BVApp.loc bld.inf
	$(SBS) -c armv6_udeb
clean-debug-armv6: bld.inf
	$(SBS) reallyclean -c armv6_udeb
freeze-debug-armv6: bld.inf
	$(SBS) freeze -c armv6_udeb
release-gcce: c:\dev\Dropbox\dev\nokia\BVApp\BVApp.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-gcce: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-gcce: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
release-armv5: c:\dev\Dropbox\dev\nokia\BVApp\BVApp.loc bld.inf
	$(SBS) -c armv5_urel
clean-release-armv5: bld.inf
	$(SBS) reallyclean -c armv5_urel
freeze-release-armv5: bld.inf
	$(SBS) freeze -c armv5_urel
release-armv6: c:\dev\Dropbox\dev\nokia\BVApp\BVApp.loc bld.inf
	$(SBS) -c armv6_urel
clean-release-armv6: bld.inf
	$(SBS) reallyclean -c armv6_urel
freeze-release-armv6: bld.inf
	$(SBS) freeze -c armv6_urel
debug-armv5-gcce4.4.1: c:\dev\Dropbox\dev\nokia\BVApp\BVApp.loc bld.inf
	$(SBS) -c arm.v5.udeb.gcce4_4_1
clean-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.udeb.gcce4_4_1
freeze-debug-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.udeb.gcce4_4_1
release-armv5-gcce4.4.1: c:\dev\Dropbox\dev\nokia\BVApp\BVApp.loc bld.inf
	$(SBS) -c arm.v5.urel.gcce4_4_1
clean-release-armv5-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v5.urel.gcce4_4_1
freeze-release-armv5-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v5.urel.gcce4_4_1
debug-armv6-gcce4.4.1: c:\dev\Dropbox\dev\nokia\BVApp\BVApp.loc bld.inf
	$(SBS) -c arm.v6.udeb.gcce4_4_1
clean-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.udeb.gcce4_4_1
freeze-debug-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.udeb.gcce4_4_1
release-armv6-gcce4.4.1: c:\dev\Dropbox\dev\nokia\BVApp\BVApp.loc bld.inf
	$(SBS) -c arm.v6.urel.gcce4_4_1
clean-release-armv6-gcce4.4.1: bld.inf
	$(SBS) reallyclean -c arm.v6.urel.gcce4_4_1
freeze-release-armv6-gcce4.4.1: bld.inf
	$(SBS) freeze -c arm.v6.urel.gcce4_4_1

export: bld.inf
	$(SBS) export -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

cleanexport: bld.inf
	$(SBS) cleanexport -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1

freeze: freeze-release

check: first

run:
	call C:/QtSDK/Symbian/SDKs/SymbianSR1Qt474/epoc32/release/winscw/udeb/BVApp.exe $(QT_RUN_OPTIONS)

runonphone: sis
	runonphone $(QT_RUN_ON_PHONE_OPTIONS) --sis BVApp.sis BVApp.exe $(QT_RUN_OPTIONS)

BVApp_template.pkg: C:/dev/Dropbox/dev/nokia/BVApp/BVApp.pro
	$(MAKE) -f $(MAKEFILE) qmake

BVApp_installer.pkg: C:/dev/Dropbox/dev/nokia/BVApp/BVApp.pro
	$(MAKE) -f $(MAKEFILE) qmake

BVApp_stub.pkg: C:/dev/Dropbox/dev/nokia/BVApp/BVApp.pro
	$(MAKE) -f $(MAKEFILE) qmake

sis: BVApp_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_sis:
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) BVApp_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_sis: BVApp_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_unsigned_sis:
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat -g $(QT_SIS_OPTIONS) -o BVApp_template.pkg $(QT_SIS_TARGET)

BVApp.sis:
	$(MAKE) -f $(MAKEFILE) sis

installer_sis: BVApp_installer.pkg sis
	$(MAKE) -f $(MAKEFILE) ok_installer_sis

ok_installer_sis: BVApp_installer.pkg
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) BVApp_installer.pkg - $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_installer_sis: BVApp_installer.pkg unsigned_sis
	$(MAKE) -f $(MAKEFILE) ok_unsigned_installer_sis

ok_unsigned_installer_sis: BVApp_installer.pkg
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat $(QT_SIS_OPTIONS) -o BVApp_installer.pkg

fail_sis_nocache:
	$(error Project has to be built or QT_SIS_TARGET environment variable has to be set before calling 'SIS' target)

stub_sis: BVApp_stub.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_stub_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_stub_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_stub_sis:
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\createpackage.bat -s $(QT_SIS_OPTIONS) BVApp_stub.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

deploy: sis
	call BVApp.sis

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc\moc_mainwindow.cpp moc\moc_chart.cpp moc\moc_tradingwindow.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc\moc_mainwindow.cpp moc\moc_chart.cpp moc\moc_tradingwindow.cpp
moc\moc_mainwindow.cpp: mainwindow.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\dev\Dropbox\dev\nokia\BVApp\mainwindow.h -o c:\dev\Dropbox\dev\nokia\BVApp\moc\moc_mainwindow.cpp

moc\moc_chart.cpp: mainwindow.h \
		chart.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\dev\Dropbox\dev\nokia\BVApp\chart.h -o c:\dev\Dropbox\dev\nokia\BVApp\moc\moc_chart.cpp

moc\moc_tradingwindow.cpp: mainwindow.h \
		tradingwindow.h
	C:\QtSDK\Symbian\SDKs\SymbianSR1Qt474\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN c:\dev\Dropbox\dev\nokia\BVApp\tradingwindow.h -o c:\dev\Dropbox\dev\nokia\BVApp\moc\moc_tradingwindow.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: ui\qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui\qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

dodistclean:
	-@ if EXIST "c:\dev\Dropbox\dev\nokia\BVApp\BVApp_template.pkg" $(DEL_FILE)  "c:\dev\Dropbox\dev\nokia\BVApp\BVApp_template.pkg"
	-@ if EXIST "c:\dev\Dropbox\dev\nokia\BVApp\BVApp_stub.pkg" $(DEL_FILE)  "c:\dev\Dropbox\dev\nokia\BVApp\BVApp_stub.pkg"
	-@ if EXIST "c:\dev\Dropbox\dev\nokia\BVApp\BVApp_installer.pkg" $(DEL_FILE)  "c:\dev\Dropbox\dev\nokia\BVApp\BVApp_installer.pkg"
	-@ if EXIST "c:\dev\Dropbox\dev\nokia\BVApp\Makefile" $(DEL_FILE)  "c:\dev\Dropbox\dev\nokia\BVApp\Makefile"
	-@ if EXIST "c:\dev\Dropbox\dev\nokia\BVApp\BVApp_exe.mmp" $(DEL_FILE)  "c:\dev\Dropbox\dev\nokia\BVApp\BVApp_exe.mmp"
	-@ if EXIST "c:\dev\Dropbox\dev\nokia\BVApp\BVApp_reg.rss" $(DEL_FILE)  "c:\dev\Dropbox\dev\nokia\BVApp\BVApp_reg.rss"
	-@ if EXIST "c:\dev\Dropbox\dev\nokia\BVApp\BVApp.rss" $(DEL_FILE)  "c:\dev\Dropbox\dev\nokia\BVApp\BVApp.rss"
	-@ if EXIST "c:\dev\Dropbox\dev\nokia\BVApp\BVApp.loc" $(DEL_FILE)  "c:\dev\Dropbox\dev\nokia\BVApp\BVApp.loc"
	-@ if EXIST "c:\dev\Dropbox\dev\nokia\BVApp\bld.inf" $(DEL_FILE)  "c:\dev\Dropbox\dev\nokia\BVApp\bld.inf"

distclean: clean dodistclean

clean: bld.inf
	-$(SBS) reallyclean --toolcheck=off -c winscw_udeb.mwccinc -c arm.v5.udeb.gcce4_4_1 -c arm.v6.udeb.gcce4_4_1 -c arm.v5.urel.gcce4_4_1 -c arm.v6.urel.gcce4_4_1


